### ISSUE TITLE
Discord link?

### ISSUE THREAD

**Issue by malakada** [hudy9x/namviek#176]
Hey -- your website for this asks people to join your Discord, but the link doesn't work. Can you hook me up? 😃

**Comment by hudy9x** [comment]
@malakada I updated the link already. Go to namviek.com to get the link or use this [link](https://discord.gg/XbYtDQYFPZ)

**Comment by MarwanBz** [comment]
Hey @hudy9x, can you assign this issue to me I want to fix that bug coz the links  not working on the footer

**Comment by hudy9x** [comment]
@MarwanBz thanks for the report. I updated the footer already
