### ISSUE TITLE
Make website Responsive

### ISSUE THREAD

**Issue by abhijain1705** [hudy9x/namviek#178]
**Is your feature request related to a problem? Please describe.**

when we view this website on mobile, it is not responsive most tools like Jira are responsive, it's easier to operate small things quicker via phone.

**Describe the solution you'd like**
website should be responsive to work on all screen devices delivering quality UX.

**Describe alternatives you've considered**
if not responsive, we should block users from using this website by putting up a banner that shows that currently, we operate on a big screen only, at least giving a direction to the user.

**Additional context**
![Screenshot 2024-05-21 182432](https://github.com/hudy9x/namviek/assets/137091099/47e34be1-f2b1-414b-903d-8b0176611f53)

**Comment by hudy9x** [comment]
Double issue: [#6](https://github.com/hudy9x/namviek-landingpage/issues/6)
