### ISSUE TITLE
Docker Implementation

### ISSUE THREAD

**Issue by hudy9x** [hudy9x/namviek#179]

**Comment by titanventura** [comment]
I'd love to pick this up!

**Comment by hudy9x** [comment]
@titanventura titan
Hmm, two guys has been implementing this issue. But I don't know their progress now. 
If you'd love to join, please join my discord and have a discussion with them 
https://discord.gg/XbYtDQYFPZ

**Comment by Quantatirsk** [comment]
+1

**Comment by hudy9x** [comment]
close #183
any improvements will be updated in another issue
