### ISSUE TITLE
Consider switching the backend from Node.js to Bun.js or Golang

### ISSUE THREAD

**Issue by hudy9x** [hudy9x/namviek#181]
## Issue
Currently, the backend is Node.js. I found that, it take a lot of memory in development mode and think it would do the same thing on production. And the packaged image is too large (>2GB)

## Solution
So, let's take a look at Bun.js and Golang for an alternatives. 

## Study
Tried Golang from a fews month ago, it's super fast and the code is pretty familiar with javascript. However, It doesn't have Class and I will have to migrate all code structure.

Bun.js is the next option. I can use Honojs. Let's do the investigation next week.

**Comment by khalt00** [comment]
So if you want to work with Golang, I'd love to contribute to your project.

**Comment by Kelvin-Riker** [comment]
If you want to improve memory usage, bun might not be your saviour here. 
Its is fast, but still uses more memory on crud operations. 

I would still consider Go, or wait for the next couple of iterations of Bun.

**Comment by binhtran432k** [comment]
Hi @hudy9x, I do not recommend you refactor your current project which is working properly. If you want to reduce the docker size, you just build by local machine and add your built directory to docker. It can be run directly with node only, so we will cutdown the size of development dependencies a lot.
