### ISSUE TITLE
Migrate yarn to pnpm for better performance

### ISSUE THREAD

**Issue by hudy9x** [hudy9x/namviek#185]

**Comment by FranciscoJBrito** [comment]
hey @hudy9x , I think we could solve this indirectly by migrating from node to bun, bun comes with its own package manager and is even faster than pnpm. What do you think? 

Ref #181

**Comment by hudy9x** [comment]
@FranciscoJBrito 
Actually i've been investigating Bun from Wed. And here's what i found so far
- We can use Hono.dev for backend
- We can use Reactjs with Bun - refer [this video](https://www.youtube.com/watch?v=jXyTIQOfTTk&t=1483s)
- Bun has it's own package manager
- It's faster

However, something still need to be verified
- Bun + prisma: https://bun.sh/guides/ecosystem/prisma  -> not verified
- Bun vs Nx: as this [documentation](https://bun.sh/guides/install/workspaces) Bun has workspace as well, so the question is, should we keep nx or migrate from nx to bun ?? 
- ...

**Comment by FranciscoJBrito** [comment]
@hudy9x I think we could try using the entire Bun ecosystem.
- package manager
- the runtime itself
- workspaces

**Comment by hudy9x** [comment]
@FranciscoJBrito 
Hmm I'll do some test before making any decision. 
Because this migration would take a lot of time.

**Comment by hudy9x** [comment]
Double #181
