### ISSUE TITLE
Feature: Make it all selfhost with mongodb

### ISSUE THREAD

**Issue by windhamwong** [hudy9x/namviek#190]
Hello,

I am happy to see the recent docker-compose update that allows people to spin up their own namviek server and play with it. However, as the MongoDB connection has hardcoded with cluster0.wd3az.mongodb.net and there is no mongodb in the docker-compose.yml.

Thus, I am writing this feature request as a reference, and I am working on making it fully selfhost with the mongo docker setup. I will stay tune on this issue post.

**Comment by zouloux** [comment]
+1 !
Indeed it would be really cool to have it fully self hosted, this is a no go for me because of this now.

**Comment by FranciscoJBrito** [comment]
@hudy9x I'll take this, try to get this upgrade for this week.

**Comment by hudy9x** [comment]
@FranciscoJBrito 
Do you have any updates for this task ?

**Comment by FranciscoJBrito** [comment]
@hudy9x it's almost ready, I have to fix some small problems and it will be ready.
