### ISSUE TITLE
Firebase google sign in

### ISSUE THREAD

**Issue by e-Naeim** [hudy9x/namviek#195]
**Describe the bug**
when trying to sign in using Google, sometimes it works but sometimes it gives me 

Firebase: Error (auth/popup-closed-by-user)
(obviously I don't close it) 

and sometimes it gives
Axios Error: Network Error or Your email or password is invalid 

it works locally ok, but on vercel not I guess, even if I added the domain to firebase.

**To Reproduce**
1. clone
2. follow installation instructions
3. set up new firebase project 
4. set the env variable 
5. deploy on vercel

**Expected behavior**
login without any issues

**Comment by hudy9x** [comment]
If you've been planning to deploy namviek to use it privately then you'll have to host the backend on cloud.
I'll update the document for it later.
