### ISSUE TITLE
Bug response on mobile redmi note 7

### ISSUE THREAD

**Issue by manhdx4** [hudy9x/namviek#203]
**Describe the bug**
I use a redmi note 7 phone to use your website on chrome browser. And noticed that the interface had a format error. I hope my contribution brings something positive.

**Screenshots**
![Screenshot_20240608-201405_Trình chạy Pixel.png](https://github.com/hudy9x/namviek/assets/166370073/84bb9902-0e4a-42e4-a8f7-cccfb8e78168)

**Smartphone**
 - Device: Xiaomi Redmi Note 7
 - Browser: Chrome

**Comment by sskhan1** [comment]
The application's UI is not properly responsive on mobile devices. If this is a priority, I can work on improving the UI's responsiveness. Could the project maintainer please confirm?

**Comment by hudy9x** [comment]
@manhdx4 @sskhan1 
issue duplicates [here](https://github.com/hudy9x/namviek-landingpage/issues/6)
