### ISSUE TITLE
Feature: Add Deployment Workflow Buttons to README

### ISSUE THREAD

**Issue by FranciscoJBrito** [hudy9x/namviek#214]
Add deployment workflow buttons to the project's README file. These buttons will allow users to easily deploy the project to various cloud platforms such as DigitalOcean, Fly.io, Heroku, etc. Each cloud platform will have its own button, for example, a "Deploy to DigitalOcean" button.

![Captura de pantalla 2024-06-13 a la(s) 14 04 08](https://github.com/hudy9x/namviek/assets/90341639/5ca3d915-c031-44eb-91f7-b6638d3533ab)

**Comment by hudy9x** [comment]
resolved it
