### ISSUE TITLE
Provide more info about the configuration and installation for self hosted

### ISSUE THREAD

**Issue by danysz** [hudy9x/namviek#222]
1. Created a Linux server
2. Installed node, redis, mongo
3. Created Firebase project
4. Installed the software
5. configure in the env partial because there is missing information about following parameters :
- NEXT_PUBLIC_PUSHER_INSTANCE_ID= ?
- PUSHER_INSTANCE_ID= I used this one with the data from pusher.
- FIREBASE_CLIENT_EMAIL= ?
- FIREBASE_PRIVATE_KEY= I put a path to the json file with admin key (please confirm)
- NEXT_PUBLIC_FIREBASE_CLIENT_CONFIG=?

After all of it, I am still getting the error :
"Firebase admin missing configuration"
The path is correct, I enabled Authentication in the Firebase project but still have this error.

Please advice.

**Comment by hudy9x** [comment]
@danysz I've been working on this issue and soon I'll publish a post about "how to deploy namviek"

1/ Back to your issue, `NEXT_PUBLIC_PUSHER_INSTANCE_ID` and `PUSHER_INSTANCE_ID` are same. So duplicate it.

2/ Next is `NEXT_PUBLIC_FIREBASE_CLIENT_CONFIG`. This variable stores all firebase client config that you got from Firebase console.
Just copy all of it and paste to that variable

![image](https://github.com/hudy9x/namviek/assets/95471659/dcfbf5b2-9622-4c98-b0b6-3745e3872dab)

Something like below

```
NEXT_PUBLIC_FIREBASE_CLIENT_CONFIG={"apiKey":"*********","authDomain":"namviek-********.firebaseapp.com","projectId":"namviek-********","storageBucket":"namviek-********.appspot.com","messagingSenderId":"123123123123","appId":"1:123123123:web:w234234234","measurementId":"G-********"}
```

3/ Finally, `FIREBASE_CLIENT_EMAIL` and `FIREBASE_PRIVATE_KEY`. These are server configuration for firebase so please check out this guide [https://docs.namviek.com/doc/gmail-auth#firebase-admin-configuration](https://docs.namviek.com/doc/gmail-auth#firebase-admin-configuration)
