### ISSUE TITLE
Lỗi không gửi, nhận thông báo với pusher

### ISSUE THREAD

**Issue by phanvantam** [hudy9x/namviek#223]
**Mô tả**
Tôi bị lỗi thông báo với pusher như dưới, có vẻ như đó là một lỗi trong code.

backend  | /app/node_modules/@pusher/push-notifications-server/push-notifications.js:278
backend  |                                 new Error(
backend  |                                 ^
backend  | 
backend  | 
backend  | Error: 422 Unprocessable Entity - `users`: array items must be unique
backend  |     at IncomingMessage.<anonymous> (/app/node_modules/@pusher/push-notifications-server/push-notifications.js:278:33)
backend  |     at IncomingMessage.emit (node:events:531:35)
backend  |     at endReadableNT (node:internal/streams/readable:1696:12)
backend  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Môi trường**
Tôi sử dụng docker compose của dự án và không chỉnh sửa.

**Comment by hudy9x** [comment]
just go to pusher.com to sign up and update these following environements
https://docs.namviek.com/doc/environment#configure-push-notification-using-pusher.js
