### ISSUE TITLE
No cached ProjectGraph is available.

### ISSUE THREAD

**Issue by khayargoli** [hudy9x/namviek#244]
I have been getting this error on Windows machine:

```
yarn frontend
yarn run v1.22.22
$ nx serve ui-app

> nx run ui-app:serve:development

- ready started server on 0.0.0.0:4200, url: http://localhost:4200
Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.
If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
    at readCachedProjectGraph (D:\Fun\WorkManager\namviek\node_modules\@nx\next\node_modules\nx\src\project-graph\project-graph.js:30:15)
    at findAllProjectNodeDependencies (D:\Fun\WorkManager\namviek\node_modules\@nx\next\node_modules\nx\src\utils\project-graph-utils.js:60:115)
    at D:\Fun\WorkManager\namviek\node_modules\@nx\next\plugins\with-nx.js:89:30
    at forNextVersion (D:\Fun\WorkManager\namviek\node_modules\@nx\next\plugins\with-nx.js:289:9)
    at D:\Fun\WorkManager\namviek\node_modules\@nx\next\plugins\with-nx.js:82:13
    at Generator.next (<anonymous>)
    at fulfilled (D:\Fun\WorkManager\namviek\node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
 >  NX   Next.js app exited with code 1
   Pass --verbose to see the stacktrace.
```

**Comment by hudy9x** [comment]
Hi @khayargoli 
The error might be occurred by conflict between nx local version and nx global version.
Please remove your global and local nx version. And reinstall it with same version 

![image](https://github.com/user-attachments/assets/4faae8c0-c30c-4032-8141-964990abb56e)

**Comment by khayargoli** [comment]
Thanks @hudy9x bro, this worked now and your project is really awesome. Did you make all of this all by yourself?

Wish we had a brief youtube tutorial on this project, I am new to nx / redis and the schedulers you have used in here. Which is why I wanted to learn from your project on how these things are working together beautifully. 

cheers man!

Biswas,
from Nepal

**Comment by hudy9x** [comment]
@khayargoli 
> Did you make all of this all by yourself?

90% bro

>Wish we had a brief youtube tutorial on this project, I am new to nx / redis and the schedulers you have used in here. Which is why I wanted to learn from your project on how these things are working together beautifully.

There're 2 reason to make me build this project:
- need a tool to manage my team with low budget
- and learn monorepo, redis and other tech 🗡️ 

If you'd like to learn something, join my discord here: [https://discord.gg/XbYtDQYFPZ](https://discord.gg/XbYtDQYFPZ)
