### ISSUE TITLE
Subtask button lacks functionality

### ISSUE THREAD

**Issue by juizoi** [hudy9x/namviek#256]
**Describe the bug**
A "subtask" button by the right of each task panel doesn't seem to do anything when the user clicks it

**Expected behavior**
Expecting a nested and indented subtask to appear below the task I clicked the button on, similar to Clickup.

**Screenshots**
![image](https://github.com/user-attachments/assets/c6be29db-8d9f-4f80-8248-c8167074c0d1)

**Desktop (please complete the following information):**
 - Chrome

**Comment by hudy9x** [comment]
Oops, these two "Copy" and "Subtask" is not available this time. 
I'll remove these icons
