### ISSUE TITLE
Deleting multiple tasks at once

### ISSUE THREAD

**Issue by juizoi** [hudy9x/namviek#257]
**Is your feature request related to a problem? Please describe.**
When dealing with a high number of tasks, I'd like the functionality to batch delete a selection instead of one by one.

**Describe the solution you'd like**
Namviek already comes with a bunch of great fields to batch set through the multi-selection mode, it would be great to have another button in that menu to delete the selected items (it would also be nice to see this option in a right click context menu too). Binding it to the delete key would be cool too, with a confirm dialog.

**Comment by hudy9x** [comment]
Yep, I'll handle it
However, there's a reason that I've not implemented this before
Cause it will lead to some a feature: recover deleted tasks
So, It will take a long time to finalize both features and I'll release one by one

**Comment by hudy9x** [comment]
Added a delete button as user selects multiple tasks
Displayed a confirm box before doing delete
![image](https://github.com/user-attachments/assets/239a6af8-c318-4216-be95-0a12a4612a96)
